name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "8"

jobs:
  # Подготовка к деплою
  prepare:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      version: ${{ steps.set-version.outputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "environment=production" >> $GITHUB_OUTPUT
          fi

      - name: Set version
        id: set-version
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

  # Сборка для деплоя
  build:
    name: Build for Deployment
    runs-on: ubuntu-latest
    needs: prepare
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r apps/*/dist deployment/ 2>/dev/null || true
          cp -r apps/*/.next deployment/ 2>/dev/null || true
          cp -r packages/*/dist deployment/ 2>/dev/null || true
          cp package.json deployment/
          cp pnpm-lock.yaml deployment/
          cp pnpm-workspace.yaml deployment/

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ needs.prepare.outputs.version }}
          path: deployment/
          retention-days: 7

  # Деплой в staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.environment == 'staging'
    environment: staging
    
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-${{ needs.prepare.outputs.version }}

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment..."
          echo "Version: ${{ needs.prepare.outputs.version }}"
          # Здесь будет логика деплоя в staging
          # Например, загрузка на сервер, обновление Docker контейнеров и т.д.

      - name: Health check
        run: |
          echo "🔍 Performing health check..."
          # Здесь будет проверка работоспособности после деплоя
          sleep 10
          echo "✅ Staging deployment successful!"

  # Деплой в production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.environment == 'production'
    environment: production
    
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-${{ needs.prepare.outputs.version }}

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment..."
          echo "Version: ${{ needs.prepare.outputs.version }}"
          # Здесь будет логика деплоя в production
          # Например, загрузка на сервер, обновление Docker контейнеров и т.д.

      - name: Health check
        run: |
          echo "🔍 Performing health check..."
          # Здесь будет проверка работоспособности после деплоя
          sleep 10
          echo "✅ Production deployment successful!"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.prepare.outputs.version }}
          release_name: Release v${{ needs.prepare.outputs.version }}
          body: |
            ## Changes in this Release
            - Automated deployment from commit ${{ github.sha }}
            - Version: ${{ needs.prepare.outputs.version }}
            
            ## Deployment Details
            - Environment: Production
            - Build: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: false

  # Уведомления о деплое
  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [prepare, deploy-staging, deploy-production]
    if: always()
    
    steps:
      - name: Notify success
        if: needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success'
        run: |
          echo "✅ Deployment to ${{ needs.prepare.outputs.environment }} successful!"
          echo "Version: ${{ needs.prepare.outputs.version }}"
          
      - name: Notify failure
        if: needs.deploy-staging.result == 'failure' || needs.deploy-production.result == 'failure'
        run: |
          echo "❌ Deployment to ${{ needs.prepare.outputs.environment }} failed!"
          echo "Version: ${{ needs.prepare.outputs.version }}"
          exit 1
